version: "3.7"

services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=diesel
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=diesel_db
    volumes:
      - ./postgres_data:/var/lib/postgressql/data/

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=mateus@fiberx.com.br
      - PGADMIN_DEFAULT_PASSWORD=admin
